model:
  name: google-bert/bert-base-multilingual-cased
  num_labels: 2
  cache_dir: models

training:
  batch_size: 2
  num_epochs: 3
  learning_rate: 5e-5
  weight_decay: 0.01
  max_length: 256
  num_warmup_steps: 500
  save_model_path: "models/fine-tuned-model"

data:
  train_file: 
    - data/ViCTSD/train.csv
    - data/ViSHD/train.csv
  val_file: 
    - data/ViCTSD/dev.csv
    - data/ViSHD/dev.csv
  test_file: 
    - data/ViCTSD/test.csv
    - data/ViSHD/test.csv
